name: FluentGuitar
favicon: null
layout_spectrum: 0.14338
typography_spectrum: 0.07554
title: FluentGuitar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9e8e81'
    - '#5e544b'
    - '#3b3630'
    - '#d7cac1'
    - '#f2ebe5'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
