name: FluentGuitar
favicon: null
layout_spectrum: 0.05386822368018329
typography_spectrum: 0.36332042003050447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030102'
    - '#a291a3'
    - '#53585e'
    - '#e9c0bc'
    - '#363233'
  brandStrength: 0.6875
  lightness: 0.6224432280287147
  saturation: 0.5625
  rhythmicContrast: 0.3278814812656492
purpose: []
