typography_spectrum: 0.07554
color:
  brandColors:
    - '#9e8e81'
    - '#5e544b'
    - '#3b3630'
    - '#d7cac1'
    - '#f2ebe5'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.42276
analytics:
  google: null
  facebook: null
  twitter: null
name: FluentGuitar
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    id: cbb28845-0bfb-4010-9ae4-71cb171e1962
    type: content
favicon: null
title: Guitar is cool. Classical guitar is hot!
purpose: []
