name: FluentGuitar
favicon: null
layout_spectrum: 0.29153
typography_spectrum: 0.07554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9a8a7d'
    - '#7e7065'
    - '#5f5249'
    - '#25221d'
    - '#d0c0b3'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
