name: FluentGuitar
favicon: null
layout_spectrum: 0.14338
typography_spectrum: 0.07554
title: FluentGuitar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cc6700'
    - '#93a600'
    - '#434c39'
    - '#dbbdd5'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
